name: Android Fastlane

on:
  pull_request:
    branches: 
      - qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: install ruby bundle
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: run fastlane for QA
      run: bundle exec fastlane qa
